/// Flutter icons ZuberiIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ZuberiIcons
///      fonts:
///       - asset: fonts/ZuberiIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GenioIcons {
  GenioIcons._();

  static const _kFontFam = 'GenioIcons';
  static const String? _kFontPkg = null;


  static const IconData creditCard = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creditCard1 = IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
